### ISSUE TITLE
[SEVERE] mockito:mockBuilder : Null check operator used on a null value

### ISSUE THREAD

**Issue by sebastianbuechler** [dart-lang/mockito#661]
When running `flutter pub --verbose run build_runner build --delete-conflicting-outputs` with `mockito` 5.4.0 I get since a couple days the error:
```
[SEVERE] mockito:mockBuilder on test/setup/test_helpers.dart:

Null check operator used on a null value
```
But I have no idea how come. I did not change anything as far I as I can remember and my mockito setup worked fine for more than a year. 
I get this verbose error message, but I don't see any clue in there either:
```
[   +5 ms] pub finished with exit code 1
[   +2 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:586:7)
           <asynchronous suspension>
           #2      PackagesForwardCommand.runCommand (package:flutter_tools/src/commands/packages.dart:250:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
```

**Comment by srawlins** [comment]
This looks like a crash in the flutter_tools package. I am unfamiliar, but I would file a bug against that package.
